import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, "DATA")


def read(path):
    if not os.path.exists(path):
        return ""
    return io.open(path, encoding="utf-8").read()


demo_path = os.path.join(os.environ.get("TEMP", ""), "opencode", "demo_act.vibe")
demo = read(demo_path)
if not demo:
    demo = 'crt(file name="out.xml")\n-> show(file name="out.xml")\n'

payload = {
    "dict": read(os.path.join(DATA, "dictionary_sorted_by_type.txt")),
    "dictName": "dictionary_sorted_by_type.txt",
    "dictAction": read(os.path.join(DATA, "action.dict")),
    "dictMapping": read(os.path.join(DATA, "mapping.dict")),
    "dictOperators": read(os.path.join(DATA, "operators.dict")),
    "dictAbstracts": read(os.path.join(DATA, "abstracts.txt")),
    "protos": read(os.path.join(DATA, "protos.txt")),
    "blueprints": read(os.path.join(DATA, "blueprints.txt")),
    "syntax": read(os.path.join(DATA, "syntax.txt")),
    "demo": demo,
}

out = os.path.join(HERE, "data.js")
with io.open(out, "w", encoding="utf-8") as f:
    f.write("/* generated by gen_data.py - do not edit by hand */\n")
    f.write("var VIBEDSL_DATA = ")
    f.write(json.dumps(payload, ensure_ascii=True))
    f.write(";\n")
    f.write('if (typeof module === "object" && module.exports) module.exports = VIBEDSL_DATA;\n')
    f.write('if (typeof window !== "undefined") window.VIBEDSL_DATA = VIBEDSL_DATA;\n')

print("wrote %s (%d bytes)" % (out, os.path.getsize(out)))
print("dict=%d action=%d mapping=%d operators=%d abstracts=%d protos=%d blueprints=%d demo=%d" % (
    len(payload["dict"]), len(payload["dictAction"]), len(payload["dictMapping"]),
    len(payload["dictOperators"]), len(payload["dictAbstracts"]),
    len(payload["protos"]), len(payload["blueprints"]), len(payload["demo"])))
